package bidchaseruilayer;

import bidchaserlogiclayer.*;
import java.awt.*;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;

/**
 *
 * @author tommy
 */
public class AddNewProductForm extends JFrame
{

    private final AddNewProductHandler productHandler;

    /**
     * Creates new form AddNewProductForm
     */
    public AddNewProductForm()
    {
        initComponents();
        productHandler = new AddNewProductHandler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newProductPanel = new javax.swing.JPanel();
        productsDetailsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        endTimeList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTA = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        productTitleTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        productAddNewBtn = new javax.swing.JButton();
        productTitlelbl = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        startPriceTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        startTimeList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        addProductImageBtn = new javax.swing.JButton();
        productImageLbl = new javax.swing.JLabel();
        productStartDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jPanel1 = new javax.swing.JPanel();
        nondurrable = new javax.swing.JButton();
        durrable = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productsDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Product Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 11))); // NOI18N

        jLabel4.setText("Start Date:");

        endTimeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        endTimeList.setSelectedIndex(1);
        jScrollPane3.setViewportView(endTimeList);

        jLabel2.setText("Product Description:");

        descriptionTA.setColumns(20);
        descriptionTA.setRows(5);
        descriptionTA.setText("She's a Flyer!!!");
        jScrollPane1.setViewportView(descriptionTA);

        jLabel6.setText("End Time:");

        productTitleTxt.setText("Ford GT");

        jLabel5.setText("Start Time:");

        productAddNewBtn.setText("Start Product");
        productAddNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productAddNewBtnActionPerformed(evt);
            }
        });

        productTitlelbl.setText("Product Title:");

        jLabel.setText("Start Price:");

        startPriceTxt.setText("1000");

        startTimeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        startTimeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        startTimeList.setSelectedIndex(0);
        jScrollPane2.setViewportView(startTimeList);

        jLabel1.setText("Product Image:");

        addProductImageBtn.setText("Add Product Image");
        addProductImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductImageBtnActionPerformed(evt);
            }
        });

        productImageLbl.setText("Product Image Goes Here!");
        productImageLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout productsDetailsPanelLayout = new javax.swing.GroupLayout(productsDetailsPanel);
        productsDetailsPanel.setLayout(productsDetailsPanelLayout);
        productsDetailsPanelLayout.setHorizontalGroup(
            productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(productsDetailsPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(productAddNewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(productsDetailsPanelLayout.createSequentialGroup()
                        .addGroup(productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(productTitlelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(productTitleTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(startPriceTxt)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(productStartDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(productImageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(addProductImageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productsDetailsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3, productTitleTxt, startPriceTxt});

        productsDetailsPanelLayout.setVerticalGroup(
            productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productsDetailsPanelLayout.createSequentialGroup()
                        .addGroup(productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productTitlelbl))
                        .addGap(18, 18, 18)
                        .addGroup(productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel))
                        .addGap(18, 18, 18)
                        .addGroup(productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(productStartDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(productImageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productsDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProductImageBtn))
                .addGap(18, 18, 18)
                .addComponent(productAddNewBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout newProductPanelLayout = new javax.swing.GroupLayout(newProductPanel);
        newProductPanel.setLayout(newProductPanelLayout);
        newProductPanelLayout.setHorizontalGroup(
            newProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProductPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(productsDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        newProductPanelLayout.setVerticalGroup(
            newProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productsDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rabbit MQ Test System"));

        nondurrable.setText("Run Non-durrable Queue");
        nondurrable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nondurrableActionPerformed(evt);
            }
        });

        durrable.setText("Run Durrable Queue");
        durrable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durrableActionPerformed(evt);
            }
        });

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(durrable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addComponent(nondurrable, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(durrable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nondurrable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(newProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProductImageBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addProductImageBtnActionPerformed
    {//GEN-HEADEREND:event_addProductImageBtnActionPerformed
        productImageLbl.setText("");
        productImageLbl.setIcon(productHandler.selectProductImage(productImageLbl.getHeight(), productImageLbl.getWidth()));
    }//GEN-LAST:event_addProductImageBtnActionPerformed

    private void productAddNewBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_productAddNewBtnActionPerformed
    {//GEN-HEADEREND:event_productAddNewBtnActionPerformed
        String productTitle = productTitleTxt.getText();
        String descriptionText = descriptionTA.getText();
        String startPrice = startPriceTxt.getText();
        Date startDate = productStartDatePicker.getDate();
        String startTime = startTimeList.getSelectedValue().toString();
        String endTime = endTimeList.getSelectedValue().toString();
        Icon productIcon = productImageLbl.getIcon();
        Image productImage = ((ImageIcon) productIcon).getImage();
        validateProductDetials(productTitle, descriptionText, startPrice, startDate, startTime, endTime, productImage);
    }//GEN-LAST:event_productAddNewBtnActionPerformed

    private void durrableActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_durrableActionPerformed
    {//GEN-HEADEREND:event_durrableActionPerformed
        Calendar rightNow = Calendar.getInstance();
        Date now = rightNow.getTime();
        AuctionScheduler auctionScheduler = new AuctionScheduler();
        auctionScheduler.setupDurableAuction("productTitle", "descriptionText",
                "1000", now, "00:00", "00:10");
    }//GEN-LAST:event_durrableActionPerformed

    private void nondurrableActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nondurrableActionPerformed
    {//GEN-HEADEREND:event_nondurrableActionPerformed
        Calendar rightNow = Calendar.getInstance();
        Date now = rightNow.getTime();
        AuctionScheduler auctionScheduler = new AuctionScheduler();
        auctionScheduler.setupNonDurableAuction("productTitle", "descriptionText",
                "1000", now, "00:00", "00:10");
    }//GEN-LAST:event_nondurrableActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        openSelectActionForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void validateProductDetials(String productTitle, String descriptionText,
            String startPrice, Date startDate, String startTime, String endTime,
            Image productImage)
    {
        int titleRetval = productHandler.validateTitle(productTitle);
        if (titleRetval == ValidationCodes.VALID_TITLE)
        {
            int descriptionRetval = productHandler.validateDescription(descriptionText);
            if (descriptionRetval == ValidationCodes.VALID_DESCRIPTION)
            {
                int priceRetval = productHandler.validatePrice(startPrice);
                if (priceRetval == ValidationCodes.VALID_PRICE)
                {
                    int startDateRetval = productHandler.validateStartDate(startDate);
                    if (startDateRetval == ValidationCodes.VALID_STARTDATE)
                    {
                        int startTimeRetval = productHandler.validateStartTime(startTime);
                        if (startTimeRetval == ValidationCodes.VALID_STARTTIME)
                        {
                            int endTimeRetval = productHandler.validateEndTime(endTime);
                            if (endTimeRetval == ValidationCodes.VALID_ENDTIME)
                            {
                                int imageRetval = productHandler.validateImage(productImage);
                                if (imageRetval == ValidationCodes.VALID_IMAGE)
                                {
                                    try
                                    {
                                        String reply = productHandler.addNewProduct(productTitle,
                                                descriptionText, startPrice, startDate,
                                                startTime, endTime);
                                        JOptionPane.showMessageDialog(this, reply);
                                        openSelectActionForm();
                                    } catch (Exception ex)
                                    {
                                        Logger.getLogger(AddNewProductForm.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                } else
                                {
                                    if (imageRetval == ValidationCodes.INVAL_IMAGE_TYPE)
                                    {
                                        JOptionPane.showMessageDialog(null, "illegal image type!!!");
                                    } else
                                    {
                                        JOptionPane.showMessageDialog(null, "unknown error reading image!!!");
                                    }
                                }
                            } else
                            {
                                if (endTimeRetval == ValidationCodes.INVAL_ETIME_LEN)
                                {
                                    JOptionPane.showMessageDialog(null, "cannot be empty!!!");
                                } else if (endTimeRetval == ValidationCodes.INVAL_ETIME_TYPE)
                                {
                                    JOptionPane.showMessageDialog(null, "illegal time format!!!");
                                }
                            }
                        } else
                        {
                            if (startTimeRetval == ValidationCodes.INVAL_STTIME_LEN)
                            {
                                JOptionPane.showMessageDialog(null, "cannot be empty!!!");
                            } else if (startTimeRetval == ValidationCodes.INVAL_STTIME_TYPE)
                            {
                                JOptionPane.showMessageDialog(null, "illegal time format!!!");
                            }
                        }
                    } else
                    {
                        if (startDateRetval == ValidationCodes.INVAL_STDATE_LEN)
                        {
                            JOptionPane.showMessageDialog(null, "cannot be empty!!!");
                        } else if (startDateRetval == ValidationCodes.INVAL_STDATE_TIME)
                        {
                            JOptionPane.showMessageDialog(null, "illegal date format!!!");
                        }
                    }
                } else
                {
                    if (priceRetval == ValidationCodes.INVAL_PRICE_LEN)
                    {
                        JOptionPane.showMessageDialog(null, "cannot be empty or longer than "
                                + ValidationCodes.MAX_PRICE_LEN + " characters!!!");
                    } else if (priceRetval == ValidationCodes.INVAL_PRICE_CHARS)
                    {
                        JOptionPane.showMessageDialog(null, "cannot contain illegal characters (Non Numeric))!!!");
                    }
                }
            } else
            {
                if (descriptionRetval == ValidationCodes.INVAL_DESCR_LEN)
                {
                    JOptionPane.showMessageDialog(null, "cannot be empty or longer than 140 characters!!!");
                } else
                {
                    JOptionPane.showMessageDialog(null, "unkown error reading description text!!!");
                }
            }
        } else
        {
            if (titleRetval == ValidationCodes.INVAL_TITLE_LEN)
            {
                JOptionPane.showMessageDialog(this,
                        "Product Title Error: cannot be empty or longer than 20 characters!!!",
                        "Product Title Error",
                        JOptionPane.ERROR_MESSAGE);
            } else if (titleRetval == ValidationCodes.INVAL_TITLE_CHARS)
            {
                JOptionPane.showMessageDialog(null, "cannot contain illegal characters (Non Alpha-Numeric))!!!");
            }
        }
    }

    private void openSelectActionForm()
    {
        //
        SelectActionForm actionForm = new SelectActionForm();
        this.setVisible(false);
        actionForm.setVisible(true);
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AddNewProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AddNewProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AddNewProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AddNewProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new AddNewProductForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductImageBtn;
    private javax.swing.JTextArea descriptionTA;
    private javax.swing.JButton durrable;
    private javax.swing.JList endTimeList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel newProductPanel;
    private javax.swing.JButton nondurrable;
    private javax.swing.JButton productAddNewBtn;
    private javax.swing.JLabel productImageLbl;
    private org.jdesktop.swingx.JXDatePicker productStartDatePicker;
    private javax.swing.JTextField productTitleTxt;
    private javax.swing.JLabel productTitlelbl;
    private javax.swing.JPanel productsDetailsPanel;
    private javax.swing.JTextField startPriceTxt;
    private javax.swing.JList startTimeList;
    // End of variables declaration//GEN-END:variables

}
