package bidchaseruilayer;

import bidchaserlogiclayer.*;
import java.util.*;
import javax.swing.*;
import org.bson.*;

/**
 *
 * @author tommy
 */
public class DisplayAuctionsForm extends javax.swing.JFrame
{

    DisplayAuctionsHandler mDisplayAuctionsHandler;

    /**
     * Creates new form DisplayAuctionsForm
     */
    public DisplayAuctionsForm()
    {
        initComponents();
        mDisplayAuctionsHandler = new DisplayAuctionsHandler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        allAuctionsBtn = new javax.swing.JButton();
        memberAuctionsBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayAllList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayMemList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        allAuctionsBtn.setText("Display All Auctions");
        allAuctionsBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                allAuctionsBtnActionPerformed(evt);
            }
        });

        memberAuctionsBtn.setText("Display Member Auctions");
        memberAuctionsBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                memberAuctionsBtnActionPerformed(evt);
            }
        });

        displayAllList.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        displayAllList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(displayAllList);

        displayMemList.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(displayMemList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allAuctionsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(memberAuctionsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 596, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {allAuctionsBtn, memberAuctionsBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(allAuctionsBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberAuctionsBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allAuctionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allAuctionsBtnActionPerformed
        // TODO add your handling code here:
        List<Document> currentsProducts = mDisplayAuctionsHandler.findAllProducts();
        // JAVA API JList
        DefaultListModel<String> model = new DefaultListModel<>();
        System.out.println("Array Size: " + currentsProducts.size());
        for (int i = 0; i < currentsProducts.size(); i++)
        {
            System.out.println("allAuctionsBtnActionPerformed()" + currentsProducts.get(i).toJson());
            //TODO: only display current auctions
            model.add(i, currentsProducts.get(i).toJson());
            displayAllList.setModel(model);
            displayAllList.setSelectedIndex(i);
        }
    }//GEN-LAST:event_allAuctionsBtnActionPerformed

    private void memberAuctionsBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_memberAuctionsBtnActionPerformed
    {//GEN-HEADEREND:event_memberAuctionsBtnActionPerformed
        // TODO add your handling code here:
        List<Document> currentsProducts = mDisplayAuctionsHandler.findAllProducts();
        BidChaserMember member = new BidChaserMember();
        DefaultListModel<String> model = new DefaultListModel<>();
        System.out.println("Array Size: " + currentsProducts.size());
        for (int i = 0; i < currentsProducts.size(); i++)
        {
            System.out.println("allAuctionsBtnActionPerformed()" + currentsProducts.get(i).toJson());
            // String jsonowername = currentsProducts.get(i).toJson().getOwner();
            // if (member.getUsername().equalsIgnoreCase(jsonowername))
            // {
            model.add(i, currentsProducts.get(i).toJson());
            // }
            displayAllList.setModel(model);
            displayAllList.setSelectedIndex(i);
        }
    }//GEN-LAST:event_memberAuctionsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(DisplayAuctionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(DisplayAuctionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(DisplayAuctionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(DisplayAuctionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new DisplayAuctionsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allAuctionsBtn;
    private javax.swing.JList displayAllList;
    private javax.swing.JList displayMemList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton memberAuctionsBtn;
    // End of variables declaration//GEN-END:variables
}
