package bidchaseruilayer;

import bidchaserlogiclayer.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author tommy
 */

// Jenkins Github Plugin Test 4


public class RegisterForm extends javax.swing.JFrame
{
    private final RegisterHandler regHandler;
    /**
     * Creates new form RegisterForm
     */
    public RegisterForm()
    {
        initComponents();
        regHandler = new RegisterHandler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerPanel = new javax.swing.JPanel();
        regDetailsPanel = new javax.swing.JPanel();
        regEmailTxt = new javax.swing.JTextField();
        regLastnameTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        regUsernameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        regPhoneNumTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        regPasswordF = new javax.swing.JPasswordField();
        regFirstnameTxt = new javax.swing.JTextField();
        regDOBTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        regRegBtn = new javax.swing.JButton();
        regLoginPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        regLoginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bid Chaser Registration Form", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        regDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Registration Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 11))); // NOI18N

        regEmailTxt.setText("tom.tom@gmail.com");

        regLastnameTxt.setText("tomtom");

        jLabel7.setText("Enter Email:");

        jLabel2.setText("Enter Lastname:");

        regUsernameTxt.setText("tomtom");

        jLabel5.setText("Enter DOB:");

        jLabel6.setText("Enter Phone Number:");

        regPhoneNumTxt.setText("0870000001");

        jLabel1.setText("Enter Firstname:");

        regPasswordF.setText("tomtom");

        regFirstnameTxt.setText("tomtom");

        regDOBTxt.setText("10/06/1982");
        regDOBTxt.setToolTipText("Date must in the format of: dd/mm/yyyy");

        jLabel3.setText("Enter Username:");

        jLabel4.setText("Enter Password:");

        regRegBtn.setText("Register New User");
        regRegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regRegBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regDetailsPanelLayout = new javax.swing.GroupLayout(regDetailsPanel);
        regDetailsPanel.setLayout(regDetailsPanelLayout);
        regDetailsPanelLayout.setHorizontalGroup(
            regDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(regDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regDetailsPanelLayout.createSequentialGroup()
                        .addGroup(regDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(regDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regFirstnameTxt)
                            .addComponent(regLastnameTxt)
                            .addComponent(regUsernameTxt)
                            .addComponent(regPasswordF)
                            .addComponent(regDOBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regPhoneNumTxt)
                            .addComponent(regEmailTxt))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(regRegBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        regDetailsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {regDOBTxt, regEmailTxt, regFirstnameTxt, regLastnameTxt, regPasswordF, regPhoneNumTxt, regUsernameTxt});

        regDetailsPanelLayout.setVerticalGroup(
            regDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(regDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(regFirstnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(regLastnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(regUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(regPasswordF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(regDOBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(regPhoneNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(regEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(regRegBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        regDetailsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {regDOBTxt, regEmailTxt, regFirstnameTxt, regLastnameTxt, regPasswordF, regPhoneNumTxt, regUsernameTxt});

        regLoginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Already Registered?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 11))); // NOI18N

        jLabel8.setText("Already Registered:");

        regLoginBtn.setText("Click Here");
        regLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regLoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regLoginPanelLayout = new javax.swing.GroupLayout(regLoginPanel);
        regLoginPanel.setLayout(regLoginPanelLayout);
        regLoginPanelLayout.setHorizontalGroup(
            regLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regLoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        regLoginPanelLayout.setVerticalGroup(
            regLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(regLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(regLoginBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(regLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(regDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(regLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regLoginBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_regLoginBtnActionPerformed
    {//GEN-HEADEREND:event_regLoginBtnActionPerformed
        openLoginForm();
    }//GEN-LAST:event_regLoginBtnActionPerformed

    private void regRegBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_regRegBtnActionPerformed
    {//GEN-HEADEREND:event_regRegBtnActionPerformed
        String fname = regFirstnameTxt.getText();
        String lname = regLastnameTxt.getText();
        String uname = regUsernameTxt.getText();
        String pword = Arrays.toString(regPasswordF.getPassword());
        String dob = regDOBTxt.getText();
        String pnum = regPhoneNumTxt.getText();
        String email = regEmailTxt.getText();
       
           
        int fnameRetval = regHandler.validateFirstname(fname);
        if (fnameRetval == ValidationCodes.VALID_FIRSTNAME)
        {
           int lnameRetval = regHandler.validateLastname(lname);
            if (lnameRetval == ValidationCodes.VALID_SURNAME)
            {
               int unameRetval  = regHandler.validateUsername(uname);
                if (unameRetval == ValidationCodes.VALID_USERNAME)
                {
                   int pwordRetval = regHandler.validatePassword(pword.trim());
                    if (pwordRetval == ValidationCodes.VALID_PASSWORD)
                    {
                       int dobRetval = regHandler.validateDOB(dob);
                        if (dobRetval == ValidationCodes.VALID_DOB)
                        {
                           int pnumRetval = regHandler.validatePhoneNumber(pnum);
                            if (pnumRetval == ValidationCodes.VALID_PHONENUMBER)
                            {
                               int emailRetval = regHandler.validateEmail(email);
                                if (emailRetval == ValidationCodes.VALID_EMAIL)
                                {
                                    System.out.println(uname + ": Details Validated");
                                    
                                    String reply = 
                                    regHandler.registerNewMember(
                                    fname, lname, uname, pword, dob, 
                                    pnum, email);
                                    
                                    JOptionPane.showMessageDialog(null, reply);
                                    
                                    //A global variable that is used to store
                                    //the username for each session                                    
                                    BidChaserMember.setUsername(uname);
                                    
                                    openSelectActionForm();
                                }
                                else
                                {
                                    if (emailRetval == ValidationCodes.INVALID_EMAIL)
                                    {
                                        JOptionPane.showMessageDialog(null, "email is invalid, must!!!\n"
                                                + "email cannot must be in the format of firstname.lastname@emailprovider.domain\n"
                                                + "or firstname@emailprovider.domain");
                                    }
                                   
                                }
                            }
                            else
                            {
                                if(pnumRetval == ValidationCodes.INVAL_PNUM_LEN)
                                {
                                    JOptionPane.showMessageDialog(null, "phone number length!!!\n"
                                        + "Current length: " + pword.length() + "\n"
                                        + "Max Length: " + ValidationCodes.MAX_PNUM_LEN);
                                }
                                 else if (pnumRetval == ValidationCodes.INVAL_PNUM_CHARS)
                                {
                                    JOptionPane.showMessageDialog(null, "phone number contains illegal characters!");
                                }
                            }
                        }
                        else
                        {
                            if(dobRetval == ValidationCodes.INVALID_DOB)
                            {
                                JOptionPane.showMessageDialog(null, "invalid date of birth format!!!\n"
                                        + "date of birth must be in the format of dd/mm/yyyy.");
                            }
                        }
                    }
                    else
                    {
                        if (pwordRetval == ValidationCodes.INVAL_PWORD_LEN)
                        {
                            JOptionPane.showMessageDialog(null, "invalid password length!!!\n"
                                    + "Current length: " + pword.length() + "\n"
                                    + "Max Length: " + ValidationCodes.MAX_PWORD_LEN);
                        }
                        else if (pwordRetval ==ValidationCodes.INVAL_PWORD_CHARS)
                        {
                            JOptionPane.showMessageDialog(null, "password contains illegal characters!!!");
                        }
                    }
                }
                else
                {
                    if (unameRetval == ValidationCodes.INVAL_UNAME_CHAR)
                    {
                        JOptionPane.showMessageDialog(null, "username first character fail");
                    }
                    else if (unameRetval ==ValidationCodes.INVAL_UNAME_LEN)
                    {
                        JOptionPane.showMessageDialog(null, "username length fail");
                    }
                    else if (unameRetval == ValidationCodes.INVAL_UNAME_EX)
                    {
                        JOptionPane.showMessageDialog(null, "Username Already exists!!!");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "username fail");
                    }
                }
            }
            else
            {
                if (lnameRetval == ValidationCodes.INVAL_SNAME_CHAR)
                {
                    JOptionPane.showMessageDialog(null, "last first character fail");
                }
                else if (lnameRetval == ValidationCodes.INVAL_SNAME_LEN)
                {
                    JOptionPane.showMessageDialog(null, "last length fail");
                }
                else if (lnameRetval == ValidationCodes.INVAL_SNAME_CHARS)
                {
                    JOptionPane.showMessageDialog(null, "last characters fail");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "surname fail");
                }
            }
        }
        else
        {
            if (fnameRetval == ValidationCodes.INVAL_FNAME_CHAR)
            {
                JOptionPane.showMessageDialog(null, "firstname first character fail");
            }
            else if (fnameRetval == ValidationCodes.INVAL_FNAME_LEN)
            {
                JOptionPane.showMessageDialog(null, "firstname length fail");
            }
            else if (fnameRetval == ValidationCodes.INVAL_FNAME_CHARS)
            {
                JOptionPane.showMessageDialog(null, "firstname characters fail");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "firstname fail");
            }
        }
    }//GEN-LAST:event_regRegBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField regDOBTxt;
    private javax.swing.JPanel regDetailsPanel;
    private javax.swing.JTextField regEmailTxt;
    private javax.swing.JTextField regFirstnameTxt;
    private javax.swing.JTextField regLastnameTxt;
    private javax.swing.JButton regLoginBtn;
    private javax.swing.JPanel regLoginPanel;
    private javax.swing.JPasswordField regPasswordF;
    private javax.swing.JTextField regPhoneNumTxt;
    private javax.swing.JButton regRegBtn;
    private javax.swing.JTextField regUsernameTxt;
    private javax.swing.JPanel registerPanel;
    // End of variables declaration//GEN-END:variables

    private void openLoginForm()
    {
        // create new LoginForm Object
        LoginForm logForm = new LoginForm();
        
        // close current window
        this.setVisible(false);
        
        // open LoginForm
        logForm.setVisible(true);
    }

    private void openSelectActionForm()
    {
        // 
        SelectActionForm actionForm = new SelectActionForm();
        
        this.setVisible(false);
        
        actionForm.setVisible(true);
    }
}
